#!/bin/bash

EXP=heps_43h22_tg3
EXP_USER=snh
EXP_GROUP=se

YYMM=202105

VFLD_WRK=$SCRATCH/vobs

mkdir -p $VFLD_WRK/$EXP

cd $VFLD_WRK/$EXP

echo "Handle vfld files in $PWD"

for F in $( find /hpc/perm/ms/$EXP_GROUP/$EXP_USER/HARMONIE/archive/$EXP/archive/extract/ -name "vobs${YYMM}*.gz" ) ; do
 echo " Unpack $F"
 tar -zxf $F 
done
